### ISSUE TITLE
Nuget and project splitting

### ISSUE THREAD

**Issue by redbaty** [WPF-Forge/Forge.Forms#14]
#### Tasks
- [ ] Create nuget packages (Appveyor)
- [ ] Split projects into separate repos.

**Comment by EdonGashi** [comment]
It gets too complicated to split each package in a repository, because all plugins depend on the core lib.

I created a structure like this: Each package will have its own folder in root. Those folders will contain its solution file, a docs folder, and a src folder. In the docs folder we document the plugins, and inside src we place the project file and an optional demo. The project files will reference `/Forge.Forms/src/Forge.Forms/Forge.Forms.csproj`. I have no clue how we will handle nugets, let's see if this tool can help us http://nuproj.net/
