### ISSUE TITLE
In Demo Examples opening a window dialog causes exception

### ISSUE THREAD

**Issue by Mrxx99** [WPF-Forge/Forge.Forms#35]
When clicking a button to show a dialog window I get an exception that MahApps.Metro or one of it's dependencies was not found (HRESULT: 0x80131040: The located assembly's manifest definition does not match the assembly reference).

Steps to reproduce:
- Start Demo Application
- Go to Examples
- Go To Dialogs
- Under "Windows" click any of the buttons.

**Comment by edongashi** [comment]
Hi @Mrxx99, thanks for the report.

I am aware of that. It's because of version mismatches in `Mahapps.Metro`. I'm unable to update the  Material.Application framework because I don't have publish rights to the NuGet package. I will try to gain access and hopefully it will be resolved (cc @redbaty). However, this should not be a problem for apps outside of the demo.

It has always been a pain dealing with these dependencies. Best solution to this is getting rid of them and moving them to separate packages, thus leaving the base clean. Any other suggestions are welcome.

**Comment by redbaty** [comment]
> It has always been a pain dealing with these dependencies. Best solution to this is getting rid of them and moving them to separate packages, thus leaving the base clean. Any other suggestions are welcome.

The newly added PackageReference (since csproj 2017) is actually getting pretty good at resolving these type of stuff!

Anyway I'll updates dependencies on the Forge.Application soon (Prob tonight)

**Comment by edongashi** [comment]
@redbaty please do so if you can. The demo still references `Material.Application`, so an easy fix would be updating that; otherwise we should migrate to `Forge.Application`.
